# Generated by Django 2.0.4 on 2018-05-03 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('en_title', models.CharField(default='', help_text='Type the english translation', max_length=60, verbose_name='English title text')),
                ('content', models.TextField()),
                ('en_content', models.TextField(default='', help_text='Type the english translation', verbose_name='English content')),
                ('experience', models.IntegerField(default=1, verbose_name='Years of experience')),
                ('employees', models.IntegerField(default=1, verbose_name='Number of employees')),
                ('orders', models.IntegerField(default=1, verbose_name='Number of orders')),
                ('clients', models.IntegerField(default=1, verbose_name='Number of clients')),
                ('youtube_vid', embed_video.fields.EmbedVideoField(default=None, help_text='For example: https://www.youtube.com/watch?v=oBT4FR84PSg', verbose_name='Youtube video link')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('en_name', models.CharField(default='', help_text='Type the english translation', max_length=60, verbose_name='English name')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('en_name', models.CharField(default='', help_text='Type name in english', max_length=60, verbose_name='English client name')),
                ('image', models.ImageField(null=True, upload_to='clients')),
                ('client_since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('en_address', models.CharField(help_text='Type address in english', max_length=50, verbose_name='Address in english')),
                ('telephone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=255)),
                ('en_title_text', models.CharField(default='', help_text='Type the english translation', max_length=255, verbose_name='English title text')),
            ],
        ),
        migrations.CreateModel(
            name='HeadSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='head_slider')),
            ],
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('sent', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('en_title', models.CharField(default='', help_text='Type in english translation', max_length=50, verbose_name='English title')),
                ('image', models.ImageField(null=True, upload_to='principles')),
                ('content', models.TextField()),
                ('en_content', models.TextField(default='', help_text='Type in english translation', verbose_name='English content')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('en_title', models.CharField(help_text='Type in english translation', max_length=120, verbose_name='English title')),
                ('client_name', models.CharField(blank=True, max_length=50)),
                ('en_client_name', models.CharField(blank=True, default='', help_text='Type name in english', max_length=50, verbose_name='English client name')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('en_address', models.CharField(blank=True, help_text='Type address in english', max_length=100, verbose_name='English address')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('content', models.TextField()),
                ('en_content', models.TextField(default='', help_text='Type the english translation', verbose_name='English content')),
                ('mini_text', models.CharField(default=None, help_text='First material, Second material', max_length=255, verbose_name='Material')),
                ('en_mini_text', models.CharField(default='', help_text='Type in english, For example: First material, Second material', max_length=255, verbose_name='English Material')),
                ('live', models.BooleanField(default=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-publish', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='projects_gallery')),
                ('product', models.ForeignKey(help_text='Choose a project', on_delete=django.db.models.deletion.CASCADE, to='main.Product', verbose_name='The product')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('en_title', models.CharField(default='', help_text='Type in english', max_length=255, verbose_name='English title')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('en_content', models.TextField(default='', help_text='Type the english translation', verbose_name='English content')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='services', verbose_name='Service image')),
                ('live', models.BooleanField(default=True)),
                ('mini_text', models.CharField(default=None, help_text='First material, Second material', max_length=255, verbose_name='Material')),
                ('en_mini_text', models.CharField(default='', help_text='Type in english, For example: First material, Second material', max_length=255, verbose_name='English Material')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=60)),
                ('symbol', models.CharField(help_text='Доступныеvk, odnoklassniki, facebook, twitter, instagram', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False)),
                ('subscribed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('en_name', models.CharField(default='', help_text='Type name in english', max_length=60, verbose_name='English employee name')),
                ('image', models.ImageField(null=True, upload_to='team')),
                ('position', models.CharField(max_length=60, verbose_name='Position')),
                ('en_position', models.CharField(default='', help_text='Type name in english', max_length=60, verbose_name='Position in english')),
                ('employee_since', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('en_fullname', models.CharField(default='', help_text='Type fullname in english', max_length=100, verbose_name='English fullname')),
                ('client', models.CharField(help_text='For example: megacom, oobamarket, oshka', max_length=50)),
                ('en_client', models.CharField(default='', help_text='Type name in english', max_length=50, verbose_name='English client')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials', verbose_name='Client image')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='testimonials', verbose_name='Logo image')),
                ('content', models.TextField()),
                ('en_content', models.TextField(default='', help_text='Type the english translation', verbose_name='English content')),
                ('live', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.CharField(help_text='Напишите код назначение, например: X8Z8okhkjv8', max_length=20)),
            ],
        ),
    ]
