# Generated by Django 2.0.4 on 2018-05-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180503_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='symbol',
            field=models.CharField(help_text='Доступные: vk, odnoklassniki, facebook, twitter, instagram', max_length=13),
        ),
    ]
