# Generated by Django 2.0.4 on 2018-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180504_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='youtube_vid',
            field=models.CharField(help_text='Type the youtube embeded code, for example: X8Z8okhkjv8', max_length=20),
        ),
    ]
