# Generated by Django 2.0.4 on 2018-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180504_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Video')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='social',
            name='symbol',
            field=models.CharField(help_text='Available: vk, odnoklassniki, facebook, twitter, instagram', max_length=13),
        ),
    ]
